-- Supabase Schema Migration

-- Safe bootstrap schema. This script does not drop existing records.

-- Projects Table
CREATE TABLE IF NOT EXISTS projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    client TEXT,
    location TEXT,
    start TEXT,
    "end" TEXT,
    budget NUMERIC,
    status TEXT,
    progress NUMERIC,
    manager TEXT
);

-- Workers Table
CREATE TABLE IF NOT EXISTS workers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id TEXT,
    name TEXT UNIQUE NOT NULL,
    age NUMERIC,
    experience NUMERIC,
    role TEXT,
    salary NUMERIC,
    join_date TEXT,
    phone TEXT,
    project TEXT REFERENCES projects(name) ON DELETE SET NULL ON UPDATE CASCADE,
    status TEXT,
    wage NUMERIC,
    notes TEXT
);

-- Materials Table
CREATE TABLE IF NOT EXISTS materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    category TEXT,
    quantity NUMERIC,
    unit TEXT,
    threshold NUMERIC,
    cost NUMERIC,
    supplier TEXT,
    project TEXT REFERENCES projects(name) ON DELETE SET NULL ON UPDATE CASCADE
);

-- Expenses Table
CREATE TABLE IF NOT EXISTS expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    category TEXT,
    amount NUMERIC,
    date TEXT,
    project TEXT REFERENCES projects(name) ON DELETE SET NULL ON UPDATE CASCADE,
    notes TEXT
);

-- Tasks Table
CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    project TEXT REFERENCES projects(name) ON DELETE SET NULL ON UPDATE CASCADE,
    assignee TEXT REFERENCES workers(name) ON DELETE SET NULL ON UPDATE CASCADE,
    start TEXT,
    due TEXT,
    status TEXT,
    priority TEXT
);

-- Enable Row Level Security (RLS)
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE workers ENABLE ROW LEVEL SECURITY;
ALTER TABLE materials ENABLE ROW LEVEL SECURITY;
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;

-- Signed-in team members share one workspace. Disable public sign-ups and
-- invite only trusted users from Supabase Auth before exposing this project.
DROP POLICY IF EXISTS "Allow public access" ON projects;
DROP POLICY IF EXISTS "Allow public access" ON workers;
DROP POLICY IF EXISTS "Allow public access" ON materials;
DROP POLICY IF EXISTS "Allow public access" ON expenses;
DROP POLICY IF EXISTS "Allow public access" ON tasks;
DROP POLICY IF EXISTS "Authenticated team can manage projects" ON projects;
DROP POLICY IF EXISTS "Authenticated team can manage workers" ON workers;
DROP POLICY IF EXISTS "Authenticated team can manage materials" ON materials;
DROP POLICY IF EXISTS "Authenticated team can manage expenses" ON expenses;
DROP POLICY IF EXISTS "Authenticated team can manage tasks" ON tasks;
CREATE POLICY "Authenticated team can manage projects" ON projects FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated team can manage workers" ON workers FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated team can manage materials" ON materials FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated team can manage expenses" ON expenses FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated team can manage tasks" ON tasks FOR ALL TO authenticated USING (true) WITH CHECK (true);
REVOKE ALL ON TABLE projects, workers, materials, expenses, tasks FROM anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE projects, workers, materials, expenses, tasks TO authenticated;

-- Seed Data (Initial Data)
INSERT INTO projects (id, name, client, location, start, "end", budget, status, progress, manager) VALUES
(1, 'Riverside Residences', 'Northstar Living', 'Pune, Maharashtra', '2025-11-10', '2025-12-08', 4850000, 'In Progress', 68, 'Aarav Mehta'),
(2, 'Greenfield Office Park', 'Meridian Group', 'Bengaluru, Karnataka', '2025-08-01', '2025-12-31', 7200000, 'In Progress', 42, 'Priya Nair'),
(3, 'Oakwood Community Center', 'City Development Corp.', 'Mumbai, Maharashtra', '2025-10-15', '2025-11-22', 2650000, 'In Progress', 84, 'Rohan Shah'),
(4, 'Hillview School Extension', 'Hillview Education Trust', 'Nashik, Maharashtra', '2025-06-03', '2025-12-18', 1950000, 'Completed', 100, 'Aarav Mehta'),
(5, 'Maple Street Townhomes', 'Cedar Homes', 'Hyderabad, Telangana', '2026-02-01', '2026-05-24', 3800000, 'Planning', 8, 'Priya Nair'),
(6, 'Eastside Water Works', 'Municipal Works Dept.', 'Pune, Maharashtra', '2025-09-12', '2025-11-25', 5600000, 'On Hold', 31, 'Rohan Shah')
ON CONFLICT (id) DO NOTHING;

INSERT INTO workers (id, employee_id, name, age, experience, role, salary, join_date, phone, project, status, wage, notes) VALUES
(1, 'BT-W-001', 'Vikram Singh', NULL, NULL, 'Site Supervisor', NULL, '', '+91 98765 43210', 'Riverside Residences', 'On site', 1800, ''),
(2, 'BT-W-002', 'Neha Kulkarni', NULL, NULL, 'Civil Engineer', NULL, '', '+91 98234 56781', 'Greenfield Office Park', 'On site', 2400, ''),
(3, 'BT-W-003', 'Ramesh Patil', NULL, NULL, 'Mason', NULL, '', '+91 97654 32109', 'Oakwood Community Center', 'On site', 950, ''),
(4, 'BT-W-004', 'Imran Khan', NULL, NULL, 'Electrician', NULL, '', '+91 98901 23456', 'Riverside Residences', 'On leave', 1250, ''),
(5, 'BT-W-005', 'Sanjay Rao', NULL, NULL, 'Carpenter', NULL, '', '+91 98123 45670', 'Greenfield Office Park', 'On site', 1100, ''),
(6, 'BT-W-006', 'Deepak Yadav', NULL, NULL, 'Laborer', NULL, '', '+91 97412 34567', 'Oakwood Community Center', 'On site', 700, ''),
(7, 'BT-W-007', 'Anita Deshmukh', NULL, NULL, 'Plumber', NULL, '', '+91 98876 54321', 'Riverside Residences', 'On site', 1150, '')
ON CONFLICT (id) DO NOTHING;

INSERT INTO materials (id, name, category, quantity, unit, threshold, cost, supplier, project) VALUES
(1, 'OPC Cement (Grade 53)', 'Cement', 42, 'bags', 50, 390, 'BuildRight Supplies', 'Riverside Residences'),
(2, 'TMT Steel Bars (12mm)', 'Steel', 860, 'kg', 200, 68, 'Metro Steel Co.', 'Riverside Residences'),
(3, 'River Sand', 'Aggregates', 12, 'tons', 5, 1850, 'Shree Aggregates', 'Greenfield Office Park'),
(4, 'Red Clay Bricks', 'Masonry', 2800, 'pcs', 500, 9, 'Narmada Brickworks', 'Oakwood Community Center'),
(5, 'Electrical Conduit (20mm)', 'Electrical', 18, 'lengths', 25, 85, 'Electra Trade Hub', 'Riverside Residences'),
(6, 'Crushed Stone (20mm)', 'Aggregates', 28, 'tons', 8, 1250, 'Shree Aggregates', 'Oakwood Community Center')
ON CONFLICT (id) DO NOTHING;

INSERT INTO expenses (id, title, category, amount, date, project, notes) VALUES
(1, 'Foundation steel delivery', 'Materials', 164000, '2025-11-08', 'Riverside Residences', 'TMT bars, phase 2'),
(2, 'Weekly crew payroll', 'Labour', 87500, '2025-11-07', 'Riverside Residences', 'Site team, week 23'),
(3, 'Tower crane rental', 'Equipment', 62000, '2025-11-05', 'Greenfield Office Park', 'Monthly hire'),
(4, 'Concrete mixer transport', 'Transportation', 18500, '2025-11-03', 'Oakwood Community Center', ''),
(5, 'Cement and aggregates', 'Materials', 94500, '2025-11-02', 'Greenfield Office Park', 'Supplier invoice #BR-442'),
(6, 'Safety equipment', 'Other', 12800, '2025-10-31', 'Oakwood Community Center', 'PPE restock')
ON CONFLICT (id) DO NOTHING;

INSERT INTO tasks (id, title, project, assignee, start, due, status, priority) VALUES
(1, 'Pour level 4 slab', 'Riverside Residences', 'Vikram Singh', '2025-11-10', '2025-11-12', 'In Progress', 'High'),
(2, 'Electrical rough-in inspection', 'Riverside Residences', 'Imran Khan', '2025-11-11', '2025-11-14', 'Pending', 'Medium'),
(3, 'Submit structural drawings', 'Greenfield Office Park', 'Neha Kulkarni', '2025-11-10', '2025-11-16', 'In Progress', 'High'),
(4, 'Install fire safety systems', 'Oakwood Community Center', 'Sanjay Rao', '2025-11-12', '2025-11-22', 'Pending', 'Medium'),
(5, 'Finish exterior masonry', 'Oakwood Community Center', 'Ramesh Patil', '2025-11-07', '2025-11-09', 'Completed', 'Low'),
(6, 'Site utility coordination', 'Greenfield Office Park', 'Neha Kulkarni', '2025-11-13', '2025-11-27', 'Pending', 'Low')
ON CONFLICT (id) DO NOTHING;

-- Activities Table
CREATE TABLE IF NOT EXISTS activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text TEXT,
    project TEXT REFERENCES projects(name) ON DELETE CASCADE ON UPDATE CASCADE,
    time TEXT,
    color TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE activities ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE activities ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public access" ON activities;
DROP POLICY IF EXISTS "Authenticated team can manage activities" ON activities;
CREATE POLICY "Authenticated team can manage activities" ON activities FOR ALL TO authenticated USING (true) WITH CHECK (true);
REVOKE ALL ON TABLE activities FROM anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE activities TO authenticated;
DELETE FROM activities WHERE text IN (
    'Steel delivery recorded',
    'Slab inspection passed',
    'Task assigned to Neha Kulkarni',
    'Weekly payroll expense added'
);

-- Settings Table
CREATE TABLE IF NOT EXISTS settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name TEXT,
    workspace_name TEXT
);

ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public access" ON settings;
DROP POLICY IF EXISTS "Authenticated team can manage settings" ON settings;
CREATE POLICY "Authenticated team can manage settings" ON settings FOR ALL TO authenticated USING (true) WITH CHECK (true);
REVOKE ALL ON TABLE settings FROM anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE settings TO authenticated;
REVOKE ALL ON SEQUENCE projects_id_seq, workers_id_seq, materials_id_seq, expenses_id_seq, tasks_id_seq, activities_id_seq, settings_id_seq FROM anon;
GRANT USAGE, SELECT ON SEQUENCE projects_id_seq, workers_id_seq, materials_id_seq, expenses_id_seq, tasks_id_seq, activities_id_seq, settings_id_seq TO authenticated;
INSERT INTO settings (id, user_name, workspace_name) VALUES
(1, NULL, 'BuildTrack Workspace')
ON CONFLICT (id) DO NOTHING;

-- Keep identity columns ready after importing the initial sample rows.
SELECT setval(pg_get_serial_sequence('projects', 'id'), COALESCE((SELECT MAX(id) FROM projects), 1), true);
SELECT setval(pg_get_serial_sequence('workers', 'id'), COALESCE((SELECT MAX(id) FROM workers), 1), true);
SELECT setval(pg_get_serial_sequence('materials', 'id'), COALESCE((SELECT MAX(id) FROM materials), 1), true);
SELECT setval(pg_get_serial_sequence('expenses', 'id'), COALESCE((SELECT MAX(id) FROM expenses), 1), true);
SELECT setval(pg_get_serial_sequence('tasks', 'id'), COALESCE((SELECT MAX(id) FROM tasks), 1), true);
SELECT setval(pg_get_serial_sequence('activities', 'id'), COALESCE((SELECT MAX(id) FROM activities), 1), true);
SELECT setval(pg_get_serial_sequence('settings', 'id'), COALESCE((SELECT MAX(id) FROM settings), 1), true);
